[project]
name = "beeai-cli"
version = "0.0.2"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "IBM Corp." }]
requires-python = ">=3.11,<4.0"
dependencies = [
    "acp-sdk>=0.0.1",
    "beeai-sdk>=0.0.4",
    "anyio>=4.8.0",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.7.1",
    "requests>=2.32.3",
    "beeai-server==0.0.1",
]

[tool.uv.sources]
beeai-server = { workspace = true }
acp-sdk = { workspace = true }
beeai-sdk = { workspace = true }

[project.scripts]
beeai = "beeai_cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
