# check

["beeai-cli:check"]
depends = ["beeai-cli:check:*"]

["beeai-cli:check:ruff-check"]
depends = ["setup:uv"]
dir = "{{config_root}}/apps/beeai-cli"
run = "uv run ruff check --quiet"
sources = ["src/**/*.py"]
outputs = { auto = true }

["beeai-cli:check:ruff-format"]
depends = ["setup:uv"]
dir = "{{config_root}}/apps/beeai-cli"
run = "uv run ruff format --quiet --check"
sources = ["src/**/*.py"]
outputs = { auto = true }

# TODO: Enable and fix issues in separate PR
# ["beeai-cli:check:pyright"]
# dir = "{{config_root}}/apps/beeai-cli"
# run = "uv run pyright"
# sources = ["src/**/*.py"]
# outputs = { auto = true }

# fix

["beeai-cli:fix"]
depends = ["beeai-cli:fix:*"]

["beeai-cli:fix:ruff-check"]
depends = ["setup:uv"]
dir = "{{config_root}}/apps/beeai-cli"
run = "uv run ruff check --quiet --fix"
sources = ["src/**/*.py"]
outputs = { auto = true }

["beeai-cli:fix:ruff-format"]
depends = ["setup:uv"]
dir = "{{config_root}}/apps/beeai-cli"
run = "uv run ruff format --quiet"
sources = ["src/**/*.py"]
outputs = { auto = true }

# run

["beeai-cli:run"]
description = "NOTE: Use double dash to pass extra args, like `mise beeai-cli:run -- provider list`"
depends = ["setup:uv", "beeai-ui:build"]
dir = "{{cwd}}"
run = "uv run beeai"

# build

["beeai-cli:build"]
depends = ["setup:uv"]
dir = "{{config_root}}/apps/beeai-cli"
run = "rm -rf ./dist && uv build --out-dir dist"
sources = ["src/**/*.py"]
outputs = ["dist/**/*"]

# clean

["beeai-cli:clean"]
dir = "{{config_root}}/apps/beeai-cli"
run = "rm -rf ./dist"
