[project]
name = "beeai-sdk"
version = "0.0.2"
description = "BeeAI SDK"
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "acp-sdk>=0.0.1",
    "opentelemetry-exporter-otlp-proto-http>=1.30.0",
    "opentelemetry-sdk>=1.30.0",
    "pydantic>=2.10.6",
]

[tool.uv.sources]
acp-sdk = { workspace = true }
