[project]
name = "beeai-sdk"
version = "0.0.1"
description = "BeeAI SDK"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "agentcommunicationprotocol>=0.0.5",
    "opentelemetry-exporter-otlp-proto-http>=1.30.0",
    "opentelemetry-sdk>=1.30.0",
    "pydantic>=2.10.6",
]
