apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: otel-collector
    {{- include "beeai-platform.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/collector/config.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
      {{- include "beeai-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: otel-collector
        {{- include "beeai-platform.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent-container
          {{- with .Values.collector.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.collector.readinessProbe }}
          readinessProbe:
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.collector.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: otel-collector-config
              mountPath: /config
              readOnly: true
          image: {{ .Values.collector.image }}
          command:
            - /otelcol-contrib
            - --config
            - /config/base.yaml
          {{- if .Values.telemetry.sharing }}
            - --config
            - /config/beeai.yaml
          {{- end }}
            - --set
            - "receivers::otlp::protocols::http::endpoint=0.0.0.0:8335"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8335
              name: http
      volumes:
        - name: otel-collector-config
          configMap:
            name: otel-collector-cm
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
