# check

["beeai-server:check"]
depends = ["beeai-server:check:*"]

["beeai-server:check:ruff-check"]
depends = ["setup:uv"]
dir = "{{config_root}}/apps/beeai-server"
run = "uv run python -m ruff check --quiet"
sources = ["src/**/*.py"]
outputs = { auto = true }

["beeai-server:check:ruff-format"]
depends = ["setup:uv"]
dir = "{{config_root}}/apps/beeai-server"
run = "uv run python -m ruff format --quiet --check"
sources = ["src/**/*.py"]
outputs = { auto = true }

# TODO: Enable and fix issues in separate PR
# ["beeai-server:check:pyright"]
# depends = ["setup:uv"]
# dir = "{{config_root}}/apps/beeai-server"
# run = "uv run python -m pyright"
# sources = ["src/**/*.py"]
# outputs = { auto = true }

# fix

["beeai-server:fix"]
depends = ["beeai-server:fix:*"]

["beeai-server:fix:ruff-check"]
depends = ["setup:uv"]
dir = "{{config_root}}/apps/beeai-server"
run = "uv run python -m ruff check --quiet --fix"
sources = ["src/**/*.py"]
outputs = { auto = true }

["beeai-server:fix:ruff-format"]
depends = ["setup:uv"]
dir = "{{config_root}}/apps/beeai-server"
run = "uv run python -m ruff format --quiet"
sources = ["src/**/*.py"]
outputs = { auto = true }

#Â run

["beeai-server:run"]
depends = ["setup:uv", "beeai-ui:build"]
dir = "{{config_root}}/apps/beeai-server"
run = "uv run beeai-server"

# build
["beeai-server:build:requirements"]
dir = "{{config_root}}/apps/beeai-server"
run = "mkdir -p dist && uv export --no-hashes --no-emit-workspace --format requirements-txt > dist/requirements.txt"
sources = ["pyproject.toml", "src/**/*.py"]
outputs = ["dist/requirements.txt"]

["beeai-server:build"]
depends = ["setup:uv", "beeai-ui:build", "beeai-server:build:requirements"]
dir = "{{config_root}}/apps/beeai-server"
run = "rm -rf ./dist/pkg && uv build --out-dir dist/pkg"
sources = ["pyproject.toml", "src/**/*.py"]
outputs = ["dist/pkg/**/*"]

# clean

["beeai-server:clean"]
dir = "{{config_root}}/apps/beeai-server"
run = "rm -rf ./dist"

# container image

["beeai-server:image:build"]
depends = ["beeai-server:build"]
dir = "{{config_root}}/apps/beeai-server"
run = "docker build -t ghcr.io/i-am-bee/beeai-platform/beeai-server:local . --load"

["beeai-server:migrations:run"]
dir = "{{config_root}}/apps/beeai-server"
depends = ["beeai-server:dev:start"]
run = "uv run migrate"

["beeai-server:migrations:alembic"]
dir = "{{config_root}}/apps/beeai-server"
depends = ["beeai-server:dev:start"]
run = """
#!/bin/bash
set -a
source .env
set +a

cd src/beeai_server/infrastructure/persistence/migrations
alembic {{arg(name="alembic_vars", var=true)}}
"""

["beeai-server:migrations:generate"]
dir = "{{config_root}}/apps/beeai-server"
depends = ["beeai-server:dev:start"]
run = "mise run beeai-server:migrations:alembic revision --autogenerate"

["beeai-server:dev:start"]
dir = "{{config_root}}/apps/beeai-server"
depends = ["beeai-server:image:build"]
run = """
#!/bin/bash

NAMESPACE=default
VM_NAME='{{option(name="vm-name", default="beeai-local-dev")}}'
KUBECONFIG="${HOME}/.beeai/lima/${VM_NAME}/copied-from-guest/kubeconfig.yaml"
LIMA_HOME=~/.beeai/lima

export KUBECONFIG
export LIMA_HOME

[[ ! -f .env ]] && cp template.env .env

tele="telepresence --use .*${NAMESPACE}.*"
($tele list --replacements 2>/dev/null | grep -q platform) && echo "Dev environment already running" && exit

# Stopping all platform deployments
mise run beeai-server:dev:stop

if [ '{{flag(name='no-registry')}}' = 'true' ]; then
  extra_flags="--set externalRegistries=null"
fi
mise run beeai-cli:run -- platform start \
    --vm-driver=lima \
    --vm-name=${VM_NAME} \
    --import ghcr.io/i-am-bee/beeai-platform/beeai-server:local \
    --set image.tag=local $extra_flags

$tele helm install
$tele connect --namespace "$NAMESPACE"
$tele replace beeai-platform --port 18333:8333
"""

["beeai-server:dev:shell"]
raw = true
shell = "echo"
dir = "{{cwd}}"
run = """
if [[ -n "$__OLD_PS1" ]]; then
  echo "Environment for 'beeai-local-dev' is already activated. To deactivate, type 'deactivate'."
  return 0
fi

VM_NAME={{option(name="vm-name", default="beeai-local-dev")}}
echo "Activating environment for '$VM_NAME'..."

export __OLD_PS1="$PS1"
export __OLD_LIMA_HOME="$LIMA_HOME"
export __OLD_KUBECONFIG="$KUBECONFIG"

export KUBECONFIG="${HOME}/.beeai/lima/${VM_NAME}/copied-from-guest/kubeconfig.yaml"
export LIMA_HOME=~/.beeai/lima
export PS1="(${VM_NAME}) ${__OLD_PS1}"

deactivate () {
  export PS1="$__OLD_PS1"

  # Restore LIMA_HOME to its original state (set or unset)
  [[ -n "$__OLD_LIMA_HOME" ]] && export LIMA_HOME="$__OLD_LIMA_HOME" || unset LIMA_HOME
  [[ -n "$__OLD_KUBECONFIG" ]] && export KUBECONFIG="$__OLD_KUBECONFIG" || unset KUBECONFIG

  # Clean up the backup values
  unset __OLD_PS1
  unset __OLD_LIMA_HOME
  unset __OLD_KUBECONFIG
  unset -f deactivate
  echo "Environment for '$VM_NAME' deactivated."
}
"""


["beeai-server:dev:stop"]
dir = "{{config_root}}/apps/beeai-server"
run = """
#!/bin/bash
NAMESPACE=default

telepresence --use ".*${NAMESPACE}.*" uninstall --all-agents || true

# Stop all lima VMs
{% raw %}
LIMA_HOME=~/.beeai/lima limactl list -f '{{.Name}}' 2>/dev/null | sed '/^[^a-z]*$/d' | \
    xargs -rn 1 -I"{}" \
    mise run beeai-cli:run -- platform stop --vm-name="{}"
{% endraw %}

telepresence --use ".*${NAMESPACE}.*" quit
"""

["beeai-server:dev:clean"]
dir = "{{config_root}}/apps/beeai-server"
run = """
VM_NAME={{option(name="vm-name", default="beeai-local-dev")}}
mise run beeai-cli:run -- platform delete --vm-name="$VM_NAME"
"""

["beeai-server:dev:test:start"]
dir = "{{config_root}}/apps/beeai-server"
run = "mise run beeai-server:dev:start --vm-name=beeai-local-test --no-registry"

["beeai-server:dev:test:clean"]
dir = "{{config_root}}/apps/beeai-server"
run = "mise run beeai-server:dev:clean --vm-name=beeai-local-test"

["beeai-server:dev:test:shell"]
dir = "{{config_root}}/apps/beeai-server"
run = "mise run beeai-server:dev:shell --vm-name=beeai-local-test"

["beeai-server:test:e2e"]
depends = ["beeai-server:image:build"]
dir = "{{config_root}}/apps/beeai-server"
run = """
#!/bin/bash
mise run beeai-server:dev:stop
curl http://localhost:8333 >/dev/null 2>&1 && echo "Another instance at localhost:8333 is already running" && exit 2

VM_NAME=e2e-test-run
mise run beeai-cli:run -- platform start -v \
    --vm-name=${VM_NAME} \
    --import ghcr.io/i-am-bee/beeai-platform/beeai-server:local \
    --set image.tag=local --set externalRegistries=null $extra_flags

export KUBECONFIG="${HOME}/.beeai/lima/${VM_NAME}/copied-from-guest/kubeconfig.yaml"
export SERVER_URL="http://localhost:8333"
export DB_URL="postgresql+asyncpg://beeai-user:password@localhost:5432/beeai"

export LLM_API_BASE="${LLM_API_BASE:-http://host.docker.internal:11434/v1}"

kubectl port-forward svc/postgresql 5432:5432 2>/dev/null 1>&2 &
pytest -m e2e
result=$?
mise run beeai-cli:run -- platform delete --vm-name=${VM_NAME}
kill %1
exit $result
"""

["beeai-server:test:integration"]
dir = "{{config_root}}/apps/beeai-server"
depends = ["beeai-server:image:build"]
run = """
#!/bin/bash
VM_NAME=itegration-test-run
mise run beeai-server:dev:start --vm-name="$VM_NAME" --no-registry
export KUBECONFIG="${HOME}/.beeai/lima/${VM_NAME}/copied-from-guest/kubeconfig.yaml"

pytest -m integration
result=$?
exit $result
"""

