apiVersion: v2
name: beeai-platform
icon: https://raw.githubusercontent.com/i-am-bee/beeai/master/docs/logo/beeai_framework_dark.svg
description: A Helm chart for Kubernetes
type: application
version: 0.2.14
appVersion: 0.2.14
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.x.x
  - condition: seaweedfs.enabled
    name: seaweedfs
    repository: https://seaweedfs.github.io/seaweedfs/helm
    version: 4.x.x
