name: Agents

on:
  push:
    tags:
      - "agents-v*"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agent:
          # Official
          - official/beeai-framework/chat
          - official/sequential-workflow
          # Community
          - community/aider
          - community/gpt-researcher
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build temporary docker image
        uses: docker/build-push-action@v5
        with:
          context: ./agents/${{ matrix.agent }}
          push: false
          build-args: |
            RELEASE_VERSION=${{ github.ref_name }}
          load: true
          tags: tmp-agent-image
      - name: Read agent manifest
        id: agent-manifest
        run: |
          set -e
          docker run -d --rm --name=tmp-agent -p 8000:8000 -e HOST=0.0.0.0 tmp-agent-image
          success=0
          for i in {1..30}; do
            echo "Extracting manifest: attempt $i"
            response=$(curl http://localhost:8000/agents 2>/dev/null) && success=1 && break
            sleep 0.5
          done
          [[ "$success" == 1 ]] || (echo "Failed to discover agents" && exit 1)
          docker kill tmp-agent
          AGENT_MANIFEST=$(echo "$response" | base64 -w 0)
          echo "content=$AGENT_MANIFEST" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./agents/${{ matrix.agent }}
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            RELEASE_VERSION:${{ github.ref_name }}
          tags: ghcr.io/${{ github.repository }}/${{ matrix.agent }}:${{ github.ref_name }},ghcr.io/${{ github.repository }}/${{ matrix.agent }}:latest
          labels: |
            beeai.dev.agent.yaml=${{ steps.agent-manifest.outputs.content }}
