name: BeeAI SDK

on:
  push:
    tags:
      - "beeai-sdk-v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish-pypi:
    name: Publish on PyPI
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: mise beeai-sdk:build:py
      - uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          packages-dir: packages/beeai-sdk/dist-py

  publish-npm:
    name: Publish on NPM
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: mise beeai-sdk:build:js
      - run: pnpm publish --access public
        working-directory: packages/acp-typescript-sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true # https://github.com/pnpm/pnpm/issues/6435#issuecomment-1518397267
